### ISSUE TITLE
Compatibility on Windows

### ISSUE THREAD

**Issue by ghost** [TheMaxoor/osx-cool-terminal#1]
Sorry but it seems to be broken on Windows 1511.10586.164, any way to fix it ?

**Comment by theobeaudenon** [comment]
Same mistake here

**Comment by TheMaxoor** [comment]
A strong fix have been already found for that. 

## Easy Etapes

### Step 1

Go to http://www.apple.com/mac/

### Step 2

Buy something on this page

### Step 3

Throw your old hardware away

### Step 4

Now you can be like this : 😃

kek
